name: Test Global News AI

on:
  workflow_dispatch:

jobs:
 test:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

      BLOG_ID: ${{ secrets.BLOG_ID }}
      BLOGGER_CLIENT_ID: ${{ secrets.BLOGGER_CLIENT_ID }}
      BLOGGER_CLIENT_SECRET: ${{ secrets.BLOGGER_CLIENT_SECRET }}
      BLOGGER_REFRESH_TOKEN: ${{ secrets.BLOGGER_REFRESH_TOKEN }}

      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

      FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
      FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Gemini Key
        run: |
          if [ -z "$GEMINI_API_KEY" ]; then
            echo "❌ GEMINI_API_KEY is NOT available"
            exit 1
          else
            echo "✅ GEMINI_API_KEY loaded successfully"
          fi

      - name: Check OpenRouter Key
        run: |
          if [ -z "$OPENROUTER_API_KEY" ]; then
            echo "❌ OPENROUTER_API_KEY is NOT available"
            exit 1
          else
            echo "✅ OPENROUTER_API_KEY loaded successfully"
            echo "Key Length: ${#OPENROUTER_API_KEY}"
          fi

      - name: Check Cloudinary
        run: |
          if [ -z "$CLOUDINARY_API_KEY" ]; then
            echo "❌ CLOUDINARY_API_KEY missing"
            exit 1
          else
            echo "✅ Cloudinary secrets loaded"
          fi

      - name: Check Facebook
        run: |
          if [ -z "$FACEBOOK_PAGE_ID" ]; then
            echo "❌ FACEBOOK_PAGE_ID missing"
            exit 1
          else
            echo "✅ FACEBOOK_PAGE_ID loaded"
          fi

          if [ -z "$FACEBOOK_PAGE_ACCESS_TOKEN" ]; then
            echo "❌ FACEBOOK_PAGE_ACCESS_TOKEN missing"
            exit 1
          else
            echo "✅ FACEBOOK_PAGE_ACCESS_TOKEN loaded"
          fi

      - name: Run Main
        run: python main.py

      - name: Upload News Files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: news-output
          path: output/news/
